readmeの編集
uheiji/recruit-app pull request #1
Opened 2024-07-25 05:37 UTC by uheiji

2024-07-25 07:50 UTC, a-taka0401 requested changes
3点コメントしました！

2024-07-25 07:50 UTC, a-taka0401 commented on README.md
> +# 求人サイト
自己学習用のリポジトリであることを初めに書いた方がいいと思います。

2024-07-25 07:50 UTC, a-taka0401 commented on README.md
> +https://drive.google.com/file/d/1YA5uKFGQtT_mAhi5-GJC1e6w9fML63nK/view?usp=sharing
ドライブじゃなくて画像そのまま貼り付けた方が良いかなと思います！
少し特殊なやり方が必要なのでググってみてください！

2024-07-25 07:50 UTC, a-taka0401 commented on README.md
> +* larevel
LaravelとTailwindCSSですね。
この辺の間違いが嫌いな人が一定数いるので直しておきましょうか！

2024-07-25 12:41 UTC, uheiji commented
3点修正しました。確認お願いします。

2024-07-26 08:34 UTC, a-taka0401 approved these changes
LGTMです！
ただ画像に関してはgithubに直接アップロードする方法もあるのでそれも確認しておいてください。

2024-08-08 11:19 UTC, merged